name: QA PR

on:
  # Run on pushes to `master` and on all pull requests.
  push:
    branches:
      - master
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Permissions should be configured at the job level.
permissions: {}

jobs:
  QA:
    permissions:
      contents: read # To clone the repo.

    name: QA
    uses: ./.github/workflows/reusable-qa-checks.yml
