name: QA checks

on:
  workflow_call:

# Permissions should be configured at the job level.
permissions: {}

jobs:
  xmllint:
    permissions:
      contents: read # To clone the repo.

    name: 'Check XML'
    runs-on: ubuntu-latest

    env:
      XMLLINT_INDENT: '    '

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 'latest'
          coverage: none

      # Install dependencies to make sure the PHPCS XSD file is available.
      - name: Install dependencies
        run: composer install --no-dev --no-interaction --no-progress

      - name: Validate Ruleset XML file against schema
        uses: phpcsstandards/xmllint-validate@5189514594c8d5f4cf21b7e5af50f54d697973d7 # v2.0.0
        with:
          pattern: "./*/ruleset.xml"
          xsd-file: "vendor/squizlabs/php_codesniffer/phpcs.xsd"

      # Check the code-style consistency of the xml file.
      # Note: this needs xmllint, but that will be installed via the phpcsstandards/xmllint-validate action runner.
      - name: Check code style
        run: diff -B ./PHPCompatibilityWP/ruleset.xml <(xmllint --format "./PHPCompatibilityWP/ruleset.xml")

  test:
    permissions:
      contents: read # To clone the repo.

    needs: xmllint

    strategy:
      matrix:
        php: ['5.4', 'latest']
        phpcompat: ['stable']
        experimental: [false]

        include:
          - php: '7.4'
            phpcompat: 'dev-develop as 10.99.99'
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    name: "Test: PHP ${{ matrix.php }} - PHPCompat ${{ matrix.phpcompat }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL, display_errors=On, display_startup_errors=On
          coverage: none
        env:
          fail-fast: true

      - name: Conditionally update PHPCompatibility to develop version
        if: ${{ matrix.phpcompat != 'stable' }}
        run: |
          composer config minimum-stability dev
          composer require --no-update phpcompatibility/php-compatibility:"${{ matrix.phpcompat }}" --no-interaction

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      # Validate the composer.json file.
      # @link https://getcomposer.org/doc/03-cli.md#validate
      - name: Validate Composer installation
        run: composer validate --no-check-all --strict

      # Make sure that known polyfills don't trigger any errors.
      - name: Test the ruleset
        run: >
          vendor/bin/phpcs -ps ./Test/WPTest.php --standard=PHPCompatibilityWP
          --exclude=PHPCompatibility.Upgrade.LowPHP
          --runtime-set testVersion 5.2-
